### ISSUE TITLE
[suggestion] split melting and casting values

### ISSUE THREAD

**Issue by Biviho** [ACGaming/BinkersBonstruct#1]
hi! it would be really great to have separate values for casting and melting and the ability to disable ore smelting for modpack developing purpose.

what i mean by that is, taking for example a block:

        -currently the conversion rate is 1 block for 800 mb on binkers both way.

        -with this change it could be 600 mb to smelt a block 
         and cost instead 1000 mb to cast it back as a block on tinker cast
         also, by disabling ore smelting, the material have to be first smelted in a different way before used in the smelter.

this way a modpack dev could create interesting progression in smelting (like incentivize different ways to smelt, melt and cast) without having to manually create conversion recipes one by one with crafttweaker (cause they are a lot!) 

i make this suggestion based on my experience while using tinkers construct on my modpack

**Comment by ACGaming** [comment]
Great input, I'll see what I can do this weekend. 🙂

**Comment by ACGaming** [comment]
Implemented some master switches to enable/disable melting and casting recipes for respective types in 265cb7e.

**Comment by ACGaming** [comment]
Implemented separate values for melting and casting in c834b70. New version will be available on CurseForge soon!
