### ISSUE TITLE
[suggestion] value for plates and gear

### ISSUE THREAD

**Issue by Biviho** [ACGaming/BinkersBonstruct#2]
hi! a good addition would be to have also custom values for plates and gear, both melting and casting.

also a master switch for gear casting, as that looks like the only one that is missing (if there is, i might have missed it)

it would also be cool to remove casting plate for removed items showing in jei, if is a thing easy to do

**Comment by ACGaming** [comment]
Implemented configurable values for gears and plates in 22488be. A master switch for gear casting already exists. Removing casts entirely caused crashes, so they just exist for now.
